on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - run: touch aa.txt
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        # Commit message
        commit_message: TEST
        
      
